#- name: Download latest cloud-ctl
#  become: true
#  get_url:
#    url: https://cloud-ctl.s3.us-west-1.amazonaws.com/cloud-ctl
#    dest: /usr/bin/cloud-ctl
#    mode: 755
#    force: true

- name: Download pcdctl  script
  become: true
  get_url:
    url: https://pcdctl.s3.us-west-2.amazonaws.com/pcdctl-setup
    dest: /tmp/pcdctl-setup
    mode: '0755'
    force: true

- name: Execute pcdctl-setup script
  become: true
  command: /tmp/pcdctl-setup

