apiVersion: v1
kind: Secret
metadata:
  name: {{ include "node-svc-checker.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "node-svc-checker.labels" . | nindent 4 }}
type: Opaque
data:
  run.sh: |-
        {{ .Files.Get "files/run.sh" | b64enc }}
