apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-svc-checker.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "node-svc-checker.labels" . | nindent 4 }}
