namespace: nsc-system

checker:
  enabled: true
  debug: false
  nodeCheckScriptPath: "/tmp/foo.sh"
  nodeCheckScriptArgs: "-c checkLicense"
  scriptPeriodSec: 5
  failureThreshold: 4
  cordonNodeOnFailure: true
  drainNodeOnFailure: true
  taintNodeOnFailure: true
  prometheusScrapeInterval: "60s"
  okReturnCodes:
    - 0
    - 127
  nodeTaint:
    key: "nodeServiceCheckFailed"
    value: "true"
    effect: "NoSchedule"

image:
  repository: bitnami/kubectl
  pullPolicy: IfNotPresent
  tag: "1.27.8"

busybox:
  repository: busybox
  pullPolicy: IfNotPresent
  tag: "1.35"
  port: 8080

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

hostNetwork: false
hostPID: false
terminationGracePeriodSeconds: "30"

podAnnotations: {}

podSecurityContext:
  privileged: true

securityContext:
  privileged: true

priorityClassName: "system-node-critical"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 16Mi

nodeSelector: {}
  # disk: ssd

tolerations:
  - effect: NoSchedule
    operator: Exists
