apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: busyboxtest
  name: busyboxpvc1
  namespace: default
spec:
  storageClassName: ${storageclass_to_test}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: busyboxtest
  namespace: default
  labels:
    app: busybox
spec:
  volumes:
    - name: ceph-rbd-volume
      persistentVolumeClaim:
        claimName: busyboxpvc1
  containers:
    - image: busybox
      name: busybox
      command: ["/bin/sh"]
      args: ["-c", "sleep 600"]
      volumeMounts:
        - name: ceph-rbd-volume
          mountPath: /mydata
